### PR TITLE
new Hungarian 

### PR DESCRIPTION
**Pull request by EziOzoani**
[Hungarian.zip](https://github.com/ammarqureshi/Group9-Project/files/768961/Hungarian.zip)

takes user input

### CODE REVIEW

**Comment by ammarqureshi** [comment]
Ezi, could you make your project into the maven format because the build is failing.

**Comment by EziOzoani** [comment]
hopefully it should work
[HungarianAlgo.zip](https://github.com/ammarqureshi/Group9-Project/files/769393/HungarianAlgo.zip)

**Comment by EziOzoani** [comment]
[HungarianAlgo.zip](https://github.com/ammarqureshi/Group9-Project/files/785491/HungarianAlgo.zip)


- [ x] Handling the group numbers , currently not working unless the array is uniform

**Comment by EziOzoani** [comment]
[HungarianAlgo.zip](https://github.com/ammarqureshi/Group9-Project/files/785492/HungarianAlgo.zip)

[ x] Handling the group numbers , currently not working unless the array is uniform

**Comment by EziOzoani** [comment]
[HungarianAlgo.zip](https://github.com/ammarqureshi/Group9-Project/files/788542/HungarianAlgo.zip)


works fab , one slight issue with printing but yh fab

**Pull request closed without merging**
